### ISSUE TITLE
Mail sent by tendrl has incorrect subject

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/notifier#109]
All mails sent by tendrl has a same subject template `<alert_type>, <severity> threshold breached`.
 This has to be fixed to have correct mail subject

**Comment by shtripat** [comment]
The subject should be like 

`<alert type>, <resource description (e.g. Brick Status)>, <severity> <suffix>`. Suffix could be based on whether its status change alert or threshold breach alert.

**Comment by GowthamShanmugam** [comment]
@nnDarshan this issue is solved please close this issue

**Comment by nnDarshan** [comment]
Fix patch is merged. Closing this
