### ISSUE TITLE
SNMP notification handler needs host ip and community name to send notification

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/notifier#127]
pysnmp message is sent to the particular host using host IP and community name, it can be multiple IP's and multiple communities based on a number of users.  Where should these inputs come from?  if those are from etcd means we need separate API and UI change. or it can be a conf file but the problem is if a new user is added then the user has to change the config file and needs to restart notifier every time. Need suggestion.

**Comment by GowthamShanmugam** [comment]
@r0h4n @brainfunked @nthomas-redhat @shtripat @anmolbabu @anivargi

**Comment by shtripat** [comment]
Second option would not be suggested  as it needs restart etc for the service on user addition.

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat your suggestion please

**Comment by r0h4n** [comment]
@GowthamShanmugam please update this issue with conclusion

**Comment by r0h4n** [comment]
Seems like we are using config file for now
