### ISSUE TITLE
Provide the latest pysnmp package for SNMP notification

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/notifier#129]
The latest pysnmp provides lot of bug fixes, security fixes, better encryption for the sending messages and also provides reliable parser for various MIB data. The latest version of this pysnmp is not yet available in epel or any other trusted repos. The package pysnmp depends on pysmi, pycryptodome, pyasn1 packages also needs to be build along with pysnmp.

The minimum required version for the dependencies is as follows:

pyasn1 0.3.7,
pysmi 0.1.3,
pycryptodome 3.4.7

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nthomas-redhat , @shtripat , @GowthamShanmugam , please review

**Comment by r0h4n** [comment]
Is this done @TimothyAsir ?

**Comment by TimothyAsirJeyasing** [comment]
Yes its done @r0h4n , We can close this issue
