### ISSUE TITLE
Provide a way to send snmp notifications to configured destinations when there is a new tendrl detected alert

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/notifier#13]
tendrl-spec: Tendrl/specifications#18

**Comment by anmolbabu** [comment]
Spec bug: Tendrl/specifications#40

**Comment by GowthamShanmugam** [comment]
@anmolbabu is this issue is required?

**Comment by anmolbabu** [comment]
It is a stretch goal..
I would seek @brainfunked inputs before closing/retaining/marking it RFE on this issue
