### ISSUE TITLE
Values in email notification should be reasonably rounded and should contain units

### ISSUE THREAD

**Issue by dahorak** [Tendrl/notifier#138]
Some email notifications contain a value - for example:
`Memory utilization of node gluster6.example.com is 93.2913037661 which is above the WARNING threshold (80).`

I think, that the value should be rounded to some reasonable precision (for example two decimal digits), because currently the number is slightly confusing, until you notice that there is a dot after second digit...

And also the value should contain "units" (probably % in this case).

**Comment by GowthamShanmugam** [comment]
@dahorak this issue is fixed, please verify
