### ISSUE TITLE
Need lock for alerting directory in etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/notifier#139]
alerting directory in etcd is updated by different node-agent from different storage nodes. Need locking mechanism to avoid a collision.

**Comment by r0h4n** [comment]
@GowthamShanmugam Please provide example of such collision

**Comment by GowthamShanmugam** [comment]
When two or more storage nodes are trying to push volume status alert for the same volume at the same time the collision will happen. Initially, there are no alerts in etcd so all nodes are considered like this alert is new alert and push the same alert into etcd with different alert id. So here the same alert is stored multiple times. 

it will affect alert count increment also, next time when clearing alert came all nodes will update the same alert 
(i mean anyone alert which matches first with clearing alert). In this case, some duplicate alerts will remains with the same state forever.

When we introduce locking, let's take example node A also raise volume alert and node B also raise volume alert for the same volume if node A acquires lock then node B should wait for its turn. If node A updated alert in etcd, then node B can't update because of the same alert already present in etcd. So duplication will be avoided.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat the example which i explained above is occurred because of my setup issue, Actually locking not required to avoid duplicate entries. because only provisioning node is going to push alerts. 

So still locking is required to avoid a case like when node-agent is pushed warning into etcd then notifier will take the alert to notify, before notifier update delivery flag as True for particular alert node-agent replace warning alert to clearing alert. Then notifier update that delivery is true in clearing alert only. So notification will never generate for clearing alert. 
I mean notifier take warning alert from etcd, before update delivery flag if clearing event came then update flag delivery will happen in the only clearing event.

so we need to lock the alert by node-agent while updating alert into etcd, and we have to lock the alert in notifier while reading the alert and up to update delivery flag of a particular alert.

**Comment by GowthamShanmugam** [comment]
This issue is fixed, i am closing this
