### ISSUE TITLE
no events

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/notifier#158]
In the current version there's no event displayed. I checked several scenarios, disable/enable profiling, stop glusterd service, ...

![missing_events](https://user-images.githubusercontent.com/22369834/36422007-e864a488-163a-11e8-8263-6c8a8539fe59.png)

NOTE: notifications api call returns empty list

Tested version:
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch

**Comment by nthomas-redhat** [comment]
@GowthamShanmugam , can you check whether the events are generated ?

**Comment by GowthamShanmugam** [comment]
I think the renaming of cluster_id as integration_id in the message is causing an issue. Let me confirm this.

**Comment by GowthamShanmugam** [comment]
https://github.com/Tendrl/api/issues/363

**Comment by GowthamShanmugam** [comment]
This issue is fixed
