### ISSUE TITLE
[RFE] Add a way to ensure different levels of alert delivery guarantees

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/notifier#29]
Spec describing the approach for this: https://github.com/Tendrl/specifications/blob/master/specs/pluggable_alert_delivery.adoc

**Comment by GowthamShanmugam** [comment]
@anmolbabu Is this issue is still required?

**Comment by anmolbabu** [comment]
This is just nice to have but was not targeted for..
So, let me know if you want me to close it and we can reopen when targeted for..
But for now I'll change this to an RFE

**Comment by GowthamShanmugam** [comment]
@anmolbabu ok

**Comment by anmolbabu** [comment]
Closing this for now feel free to reopen when relevant
