### ISSUE TITLE
Fix PEP8 violations

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/notifier#97]
Fix all PEP8 violations

check cmd : "tox -epep8"

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this issue

**Comment by GowthamShanmugam** [comment]
@r0h4n pep8 errors are solved, notifier does not have any pep8 error now

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close  this issue
